### PR TITLE
*: remove coarse time

### LINKED ISSUE #312: Occasionally coredump when use auto flush
**Describe the bug**

After tikv/tikv#6698 introduces auto flush, TiKV coredumps occasionally in tests. The backtrace looks like following:
```
190                 unsafe { *ptr }
(gdb) bt
#0  coarsetime::instant::Instant::_recent::h2463e7aa25007767 () at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/coarsetime-0.1.12/src/instant.rs:190
#1  0x00005576071c1579 in coarsetime::instant::Instant::recent::h5f6e460e26e3ac25 () at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/coarsetime-0.1.12/src/instant.rs:78
#2  0x0000557604b6b2f9 in prometheus::metrics::MayFlush::try_flush::h49c24ea58b80d0b9 () at /home/.cargo/git/checkouts/rust-prometheus-3e1bb31763da7693/4b445b2/src/metrics.rs:42
#3  0x00005576048ff09a in _$LT$tikv..server..metrics..prometheus_static_scope_5..ResolveStoreCounterVecInner$u20$as$u20$prometheus..metrics..MayFlush$GT$::may_flush::h07757cfed788f6fb ()
    at src/server/metrics.rs:9
#4  0x0000557603f1583d in prometheus::auto_flush::AFLocalCounter$LT$T$C$V$C$D$GT$::inc::_$u7b$$u7b$closure$u7d$$u7d$::hd806721e06b8d9ff ()
    at /home/.cargo/git/checkouts/rust-prometheus-3e1bb31763da7693/4b445b2/src/auto_flush.rs:99
#5  0x0000557604361252 in std::thread::local::LocalKey$LT$T$GT$::try_with::h2afa886911809580 () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262
#6  0x000055760435dcda in std::thread::local::LocalKey$LT$T$GT$::with::h58cc57966b3e2436 () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239
#7  0x0000557603f15581 in prometheus::auto_flush::AFLocalCounter$LT$T$C$V$C$D$GT$::inc::h6263e136dfc32106 () at /home/.cargo/git/checkouts/rust-prometheus-3e1bb31763da7693/4b445b2/src/auto_flush.rs:96
```

It's related to jedisct1/rust-coarsetime#10.

### PR DESCRIPTION
**Pull request by BusyJay**
What we need is a time cache updated periodically, it's so simple that
doesn't require a library. Besides current used library appears to have
a UAF problem.

Close #312.

### CODE REVIEW

File: src/timer.rs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+/// Returns milliseconds since ANCHOR.
+///
+/// ANCHOR is some fixed point in history.
+pub fn now_millis() -> u64 {
+    let res = Instant::now();
+    let mut t = res
+        .checked_duration_since(*ANCHOR)
+        .map_or(0, |d| d.as_secs() * 1000 + d.subsec_millis() as u64);
+    let mut recent = RECENT.load(Ordering::Relaxed);
```
Comment (breeswish) [inline src/timer.rs]: Why not simply store the timestamp?

File: src/metrics.rs [hunk 2]
```diff
@@ -38,10 +39,10 @@ pub trait LocalMetric {
 pub trait MayFlush: LocalMetric {
     /// If the LocalMetric is already flushed in last `flush_interval_sec` seconds, then do nothing,
     /// else flush and update last flush time.
-    fn try_flush(&self, last_flush: &Cell<Instant>, flush_interval: coarsetime::Duration) {
-        let now = Instant::recent();
+    fn try_flush(&self, last_flush: &Cell<u64>, flush_interval: Duration) {
+        let now = timer::recent_millis();
         let last_tick = last_flush.get();
-        if now.duration_since(last_tick) < flush_interval {
+        if Duration::from_millis(now - last_tick) < flush_interval {
```
Comment (breeswish) [inline src/metrics.rs]: better not to construct `Duration` since it uses slow multiplications.. `flush_interval` can be `flush_interval_ms`.

File: src/timer.rs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    loop {
+        if recent > t {
```
[the remark this answers is not in the document]
Comment (BusyJay) [reply src/timer.rs]: Several threads call `timer::now()` at the same time.

File: src/timer.rs (hunk 1 above)
Comment (BusyJay) [reply src/timer.rs]: RECENT can go back in racy condition.

**Comment by BusyJay** [comment]
PTAL

File: src/timer.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+            t = recent;
+            break;
+        }
+        match RECENT.compare_exchange_weak(recent, t, Ordering::Relaxed, Ordering::Relaxed) {
+            Ok(_) => break,
+            Err(r) => recent = r,
+        }
+    }
+    RECENT.store(t, Ordering::Relaxed);
```
Comment (glorv) [inline src/timer.rs]: seems this store is redundant either for the first or second break condition

Comment (BusyJay) [reply src/timer.rs]: Good catch. The line is forgotten to removed, it's written before the loop.
